release start: Make the error message more clear
Instead of

  Error: Given base 'origin/release/1.2.3' is not a valid commit on
  'develop'.

print

  Error: Branch 'origin/release/1.2.3' found in the repository, but it
  is diverging from 'develop'.

This I find much more clear about what is really wrong.